### ISSUE TITLE
Multiple Controllers in Same Portable Area

### ISSUE THREAD

**Issue by msgm** [fretje/MembershipStarterKit#5]
Do you know if its possible to have multiple controllers and multiple folders within the views folder in one portable area? Or do I have to create a portable area and register seperately for each of my controllers?

**Comment by fretje** [comment]
I'm pretty sure there isn't a limitation on the number of controllers and/or views inside a portable area. Have you tried it?
Not sure what this has to do with this project, so I'm closing this one...

**Comment by msgm** [comment]
Yeah I did try it... I couldn't get it to work with a controller that has a name other than the area name... and I haven't been able to find any examples out there with multiple controllers so I was just wondering if it were possible.... or whether anyone else had tried it. Thanks for your reply anyway.
