### ISSUE TITLE
Filtering Users

### ISSUE THREAD

**Issue by rexdefuror** [fretje/MembershipStarterKit#6]
I'm in progress of learning MVC and your starter kit helped a lot in the process. Now I'm kind of stuck at not being able to sort users by role within this mvc membership kit. 

I've tried with LINQ:

```
Users = _userService
    .FindAll(index ?? 0, PageSize)
    .Where(
        x => _rolesService.GetRolesForUser(x.UserName).SequenceEqual(roles)
    ),
```

But this will of course return `IEnumerable<>` instead of `IPageList<>` as it should I tried casting it with simple `(IPageList<MembershipUser>)` prefix to `_userService` but no luck it returns bunch of logic errors.
Please help if possible. Thank you.

**Comment by fretje** [comment]
This is the original PagedList Project on github: https://github.com/TroyGoode/PagedList

I see there should be a "ToPagedList" extention method on IEnumerable... did you try that one?

**Comment by rexdefuror** [comment]
I must say I haven't. I'll try it and get back to you. Thanks
